{{- if .Values.networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "terranetes-controller.fullname" . }}-deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "terranetes-controller.fullname" . }}-apiserver
spec:
  ingress:
    - from:
      ports:
        - protocol: TCP
          port: {{ .Values.controller.port }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "terranetes-controller.name" . }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "terranetes-controller.fullname" . }}-webhooks
spec:
  ingress:
    - from:
      ports:
        - protocol: TCP
          port: {{ .Values.controller.webhooks.port }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "terranetes-controller.name" . }}
  policyTypes:
    - Ingress
{{- end }}
