{{ $namespace := .Release.Namespace }}
{{- range $index, $provider := .Values.providers }}
{{- $cloud := $provider.provider | required (printf ".Values.providers[%d].provider is required." $index) -}}
{{- $name := $provider.name | required (printf ".Values.providers[%d].name is required." $index) -}}
{{- $source := $provider.source | required (printf ".Values.providers[%d].source is required." $index) -}}
---
apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: {{ $name }}
  annotations:
    {{- range $key, $value := $provider.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  labels:
    {{- range $key, $value := $provider.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  {{- if $provider.summary }}
  summary: {{ $provider.summary }}
  {{- end }}
  source: {{ $source }}
  provider: {{ $cloud }}
  {{- if eq $provider.source "secret" }}
  secretRef:
    namespace: {{ $namespace }}
    name: {{ $provider.secret }}
  {{- end }}
  {{- if eq $provider.source "injected" }}
  serviceAccount: {{ $provider.serviceAccount }}
  {{- end }}
{{ end }}
