{{- if .Values.rbac.controller.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terranetes-controller
  annotations:
    {{ toYaml .Values.rbac.controller.annotations | indent 4 }}
{{- end }}
{{- if .Values.rbac.executor.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terranetes-executor
  annotations:
    {{ toYaml .Values.rbac.executor.annotations | indent 4 }}
{{- end }}
