---
run:
  go: "1.21"
  tests: false
  timeout: 10m
  exclude-dirs:
    - hack
    - tests

linters:
  enable:
    - asasalint
    - bodyclose
    - depguard
    - dupl
    - dupword
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - goconst
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unparam
    - unused
    - wastedassign

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/davecgh/go-spew/spew
            desc: used for debugging
          - pkg: io/ioutil
            desc: deprecated in go1.16

  gosimple:
    checks:
      - all

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  staticcheck:
    checks:
      - all

  stylecheck:
    checks:
      - all
      - -ST1003
    dot-import-whitelist:
      - github.com/onsi/ginkgo
      - github.com/onsi/gomega

issues:
  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
