---
apiVersion: terraform.appvia.io/v1alpha1
kind: Configuration
metadata:
  name: bucket
spec:
  ## Using a public repository
  module: https://github.com/appvia/terraform-private-e2e
  #
  auth:
    name: auth

  providerRef:
    name: aws

