---
apiVersion: terraform.appvia.io/v1alpha1
kind: CloudResource
metadata:
  name: bucket
spec:
  ## Is the plan this cloud configuration is associated to
  ## You can use $ kubectl get plans to view the plans available in the cluster
  plan:
    ## Is the name of the plan to use
    name:  bucket
    ## Plan can have multiple revisions, this field determines the version
    ## which you want this cloud resource to use
    revision: v0.0.1

  ## Is a reference to the provider which contains the cloud credentials.
  ## This field may of may not be optional depending on how the platform has
  ## configured the provider
  providerRef:
    ## Is the name of the provider to use
    name: aws

  writeConnectionSecretToRef:
    name: test

  variables:
    bucket: terranetes-controller-ci-bucket
