---
apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: aws
spec:
  source: secret
  provider: aws
  secretRef:
    namespace: terraform-system
    name: aws
---
apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: aws-irsa
spec:
  source: injected
  provider: aws
  serviceAccount: terraform-executor
