#
# The following provide examples of the layout of the credentials for a
# provider. For complete example take a look at the official documetation
# found https://registry.terraform.io/browse/providers
#
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: aws
  namespace: terraform-system
data:
  AWS_ACCESS_KEY_ID:
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY:
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: azure
  namespace: terraform-system
data:
  ARM_CLIENT_ID:
  ARM_CLIENT_SECRET:
  ARM_SUBSCRIPTION_ID:
  ARM_TENANT_ID:
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: google
  namespace: terraform-system
data:
  GCLOUD_KEYFILE_JSON: <JSON FILE>
