FROM alpine:3.15.4

RUN apk add ca-certificates git openssh

ADD bin/source /bin/source

RUN adduser -G nobody source -s /home/source -u 1001 -s /sbin/nologin -D
RUN chown -R source:nobody /home/source/.ssh && \
    chmod 0700 /home/source/.ssh

USER 1001

ENTRYPOINT ["/bin/source"]
