FROM golang:1.20 AS builder

ARG VERSION=latest
ARG LFLAGS

COPY . /go/src/github.com/appvia/terranetes-controller

ENV \
  CGO_ENABLED=0 \
  VERSION=$VERSION

RUN cd /go/src/github.com/appvia/terranetes-controller && make controller

FROM alpine:3.18

RUN apk add ca-certificates

COPY --from=builder /go/src/github.com/appvia/terranetes-controller/bin/controller /bin/controller

USER 65534

ENTRYPOINT ["/bin/controller"]
