---
name: Develop

on:
  push:
    branches: [develop]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  develop-images:
    uses: ./.github/workflows/images.yaml
    secrets: inherit
